Us032   update readme for running and testing
maxlilleyman/UITeamB pull request #13
Opened 2022-07-20 08:56 UTC by maxlilleyman

2022-07-20 13:05 UTC, michaelkerrigan approved these changes

2022-07-20 13:33 UTC, MatSwiKainos requested changes

2022-07-20 13:33 UTC, MatSwiKainos commented on README.md
> +3. Start application with `npm start`
UI works only when API is running in the background. I think we should add one new point with reference to an API github repo.

2022-07-21 08:23 UTC, maciekkaczor commented on README.md
> +2. Run "Git pull" to bring files up to date
I think 2 first points should be removed same as in the API readme.

2022-07-21 09:05 UTC, MatSwiKainos approved these changes

2022-07-21 09:19 UTC, maciekkaczor approved these changes

2022-07-21 10:31 UTC, boydstepnew commented on README.md
> +Tests
Let's match the headings/layout of the API readme closer

2022-07-21 12:25 UTC, boydstepnew approved these changes

2022-07-21 12:26 UTC, merged